export const REQUEST_LOGIN_WITH_APPLE = 'REQUEST_LOGIN_WITH_APPLE';
export const REQUEST_LOGIN_WITH_GOOGLE = 'REQUEST_LOGIN_WITH_GOOGLE';
export const REQUEST_LOGIN_WITH_FACEBOOK = 'REQUEST_LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_GOOGLE_SUCCESS = 'LOGIN_WITH_GOOGLE_SUCCESS';
export const LOGIN_WITH_GOOGLE_FAIL = 'LOGIN_WITH_GOOGLE_FAIL';
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'LOGIN_WITH_FACEBOOK_SUCCESS';
export const LOGIN_WITH_FACEBOOK_FAIL = 'LOGIN_WITH_FACEBOOK_FAIL';
export const LOGIN_WITH_APPLE_SUCCESS = 'LOGIN_WITH_APPLE_SUCCESS';
export const LOGIN_WITH_APPLE_FAIL = 'LOGIN_WITH_APPLE_FAIL';
export const GET_SAVED_USER_SUCCESS = 'GET_SAVED_USER_SUCCESS';
export const REQUEST_LOG_OUT = 'REQUEST_LOG_OUT';
export const LOG_OUT_SUCCESS = 'LOG_OLOG_OUT_SUCCESSUT';
export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_BOOK_INFO = 'SET_BOOK_INFO';

export const RATING_STATUS = 'RATING_STATUS';
export const STARTING_APP_TIME = 'STARTING_APP_TIME';
export const NEVER_SHOW_LOGIN_AGAIN = 'NEVER_SHOW_LOGIN_AGAIN';
export const RESET_TIME = 'RESET_TIME';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';

export const SET_LEARNING_TIMES = 'SET_LEARNING_TIMES';
export const RESET_LEARNING_TIMES = 'RESET_LEARNING_TIMES';

export const SET_LOW_DEVICE = 'SET_LOW_DEVICE';

// subjects
export const GET_LIST_SUBJECTS = 'GET_LIST_SUBJECTS';

// ads
export const GET_ALL_SCREENS_FOR_ADS = 'GET_ALL_SCREENS_FOR_ADS';
