require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'VietJack' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Pods for VietJack
  pod 'Firebase/Core', '~> 6.13.0'
  pod 'Firebase/AdMob', '~> 6.13.0'
  pod 'Firebase/Messaging', '~> 6.13.0'
  pod 'Firebase/Analytics'

  target 'VietJackTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'VietJack-tvOS' do
  # Pods for VietJack-tvOS

  target 'VietJack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
